/// Nom français des 114 sourates
final Map<int, String> surahFr = {
  1: 'Al-Fatiha',
  2: 'Al-Baqarah',
  3: 'Al-Imran',
  4: 'An-Nisa',
  5: 'Al-Ma\'idah',
  6: 'Al-An\'am',
  7: 'Al-A\'raf',
  8: 'Al-Anfal',
  9: 'At-Tawbah',
  10: 'Yunus',
  11: 'Hud',
  12: 'Yusuf',
  13: 'Ar-Ra\'d',
  14: 'Ibrahim',
  15: 'Al-Hijr',
  16: 'An-Nahl',
  17: 'Al-Isra',
  18: 'Al-Kahf',
  19: 'Maryam',
  20: 'Ta-Ha',
  21: 'Al-Anbiya',
  22: 'Al-Hajj',
  23: 'Al-Mu\'minun',
  24: 'An-Nur',
  25: 'Al-Furqan',
  26: 'Ash-Shu\'ara',
  27: 'An-Naml',
  28: 'Al-Qasas',
  29: 'Al-Ankabut',
  30: 'Ar-Rum',
  31: 'Luqman',
  32: 'As-Sajdah',
  33: 'Al-Ahzab',
  34: 'Saba',
  35: 'Fatir',
  36: 'Ya-Sin',
  37: 'As-Saffat',
  38: 'Sad',
  39: 'Az-Zumar',
  40: 'Ghafir',
  41: 'Fussilat',
  42: 'Ash-Shura',
  43: 'Az-Zukhruf',
  44: 'Ad-Dukhan',
  45: 'Al-Jathiyah',
  46: 'Al-Ahqaf',
  47: 'Muhammad',
  48: 'Al-Fath',
  49: 'Al-Hujurat',
  50: 'Qaf',
  51: 'Adh-Dhariyat',
  52: 'At-Tur',
  53: 'An-Najm',
  54: 'Al-Qamar',
  55: 'Ar-Rahman',
  56: 'Al-Waqi\'ah',
  57: 'Al-Hadid',
  58: 'Al-Mujadilah',
  59: 'Al-Hashr',
  60: 'Al-Mumtahanah',
  61: 'As-Saff',
  62: 'Al-Jumu\'ah',
  63: 'Al-Munafiqun',
  64: 'At-Taghabun',
  65: 'At-Talaq',
  66: 'At-Tahrim',
  67: 'Al-Mulk',
  68: 'Al-Qalam',
  69: 'Al-Haqqah',
  70: 'Al-Ma\'arij',
  71: 'Nuh',
  72: 'Al-Jinn',
  73: 'Al-Muzzammil',
  74: 'Al-Muddaththir',
  75: 'Al-Qiyamah',
  76: 'Al-Insan',
  77: 'Al-Mursalat',
  78: 'An-Naba',
  79: 'An-Nazi\'at',
  80: '\'Abasa',
  81: 'At-Takwir',
  82: 'Al-Infitar',
  83: 'Al-Mutaffifin',
  84: 'Al-Inshiqaq',
  85: 'Al-Buruj',
  86: 'At-Tariq',
  87: 'Al-A\'la',
  88: 'Al-Ghashiyah',
  89: 'Al-Fajr',
  90: 'Al-Balad',
  91: 'Ash-Shams',
  92: 'Al-Layl',
  93: 'Ad-Duha',
  94: 'Ash-Sharh',
  95: 'At-Tin',
  96: 'Al-\'Alaq',
  97: 'Al-Qadr',
  98: 'Al-Bayyinah',
  99: 'Az-Zalzalah',
  100: 'Al-\'Adiyat',
  101: 'Al-Qari\'ah',
  102: 'At-Takathur',
  103: 'Al-\'Asr',
  104: 'Al-Humazah',
  105: 'Al-Fil',
  106: 'Quraysh',
  107: 'Al-Ma\'un',
  108: 'Al-Kawthar',
  109: 'Al-Kafirun',
  110: 'An-Nasr',
  111: 'Al-Masad',
  112: 'Al-Ikhlas',
  113: 'Al-Falaq',
  114: 'An-Nas'
};
// EN (pour l'instant: mêmes noms translittérés que FR, mais l'app affichera "Surah" au lieu de "Sourate")
final Map<int, String> surahEn = Map<int, String>.from(surahFr);

/// Signification des 114 sourates en français
final Map<int, String> surahMeaning = {
  1: "L'Ouverture",       2: "La Vache",              3: "La Famille d'Imran",
  4: "Les Femmes",        5: "La Table Servie",        6: "Les Bestiaux",
  7: "Les Murailles",     8: "Le Butin",               9: "Le Repentir",
  10: "Jonas",            11: "Houd",                  12: "Joseph",
  13: "Le Tonnerre",      14: "Abraham",               15: "Al-Hijr",
  16: "Les Abeilles",     17: "Le Voyage Nocturne",    18: "La Caverne",
  19: "Marie",            20: "Lettres coraniques",    21: "Les Prophètes",
  22: "Le Pèlerinage",    23: "Les Croyants",          24: "La Lumière",
  25: "Le Critère",       26: "Les Poètes",            27: "Les Fourmis",
  28: "Le Récit",         29: "L'Araignée",            30: "Les Romains",
  31: "Luqman",           32: "La Prosternation",      33: "Les Coalisés",
  34: "Sabâ",             35: "Le Créateur",           36: "Lettres coraniques",
  37: "Les Rangés",       38: "Lettre coranique",      39: "Les Groupes",
  40: "Le Pardonneur",    41: "Les Versets Détaillés", 42: "La Consultation",
  43: "L'Ornement",       44: "La Fumée",              45: "L'Agenouillée",
  46: "Les Dunes",        47: "Muhammad",              48: "La Victoire",
  49: "Les Appartements", 50: "Lettre coranique",      51: "Les Vents Dispersants",
  52: "Le Mont Sinaï",    53: "L'Étoile",              54: "La Lune",
  55: "Le Tout Miséricordieux", 56: "L'Événement",     57: "Le Fer",
  58: "Celle qui Discute",59: "L'Exode",               60: "L'Éprouvée",
  61: "Le Rang",          62: "Le Vendredi",           63: "Les Hypocrites",
  64: "La Spoliation",    65: "Le Divorce",            66: "L'Interdiction",
  67: "La Royauté",       68: "La Plume",              69: "La Réalité Inéluctable",
  70: "Les Degrés",       71: "Noé",                   72: "Les Djinns",
  73: "L'Enveloppé",      74: "Le Revêtu",             75: "La Résurrection",
  76: "L'Homme",          77: "Les Envoyés",           78: "La Nouvelle",
  79: "Les Arracheurs",   80: "Il s'est renfrogné",    81: "L'Obscurcissement",
  82: "La Rupture",       83: "Les Fraudeurs",         84: "La Déchirure",
  85: "Les Constellations",86: "L'Astre Nocturne",     87: "Le Très-Haut",
  88: "L'Enveloppante",   89: "L'Aurore",              90: "La Cité",
  91: "Le Soleil",        92: "La Nuit",               93: "L'Heure Matinale",
  94: "L'Ouverture du Cœur", 95: "Le Figuier",         96: "L'Adhérence",
  97: "La Nuit du Destin",98: "La Preuve",             99: "Le Séisme",
  100: "Les Coursiers",   101: "La Fracassante",       102: "La Rivalité",
  103: "Le Temps",        104: "Le Calomniateur",      105: "L'Éléphant",
  106: "Quraysh",         107: "L'Ustensile",          108: "L'Abondance",
  109: "Les Infidèles",   110: "Le Secours",           111: "La Fibre",
  112: "La Pureté Divine",113: "L'Aube",               114: "Les Hommes",
};
